spring.application.name=teste

spring.datasource.url=jdbc:postgresql://db.piuugxhqucmvhgusjwzz.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Tatabol150506*

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


